config/routes.rb
Rails.application.routes.draw do

  resources :committees do
    member do
      get :delete
    end
  end
  
   resources :sponsors do
    member do
      get :delete
    end
  end
  
  resources :events do
    member do
      get :delete
    end
  end
  
  resources :positions do
    member do
      get :delete
    end
  end
  
  resources :divisions do
    member do
      get :delete
    end
  end
  
  resources :members do
    member do
      get :delete
    end
  end

end

app/models/committee.rb
class Committee < ActiveRecord::Base
end

app/models/division.rb
class Division < ActiveRecord::Base
    has_many :members
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
    belongs_to :position
    belongs_to :division
end

app/models/position.rb
class Position < ActiveRecord::Base
    has_many :members
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
end

app/controllers/application_controller.rb
#!!!!!!
#Don't delete this
#!!!!!!

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  
  # ***********************************************************************
  # Display committees.
  # ***********************************************************************
  def index
    @committees = Committee.order(:name)
  end

  def show
    @committee = Committee.find(params[:id])
  end

  # ***********************************************************************
  # Add a new committee.
  # ***********************************************************************
  def new
    @committee = Committee.new
  end
  
  def create
     @committee = Committee.new(committee_params)

    if @committee.save
      redirect_to(committees_path)
    else
      render("new")
    end
  end

  # ***********************************************************************
  # Update a committee.
  # ***********************************************************************
  def edit
    @committee = Committee.find(params[:id])
  end
  
  def update
    @committee = Committee.find(params[:id])

    if @committee.update_attributes(committee_params)
      redirect_to(committee_path(@committee))
    else
      render("edit")
    end
  end

  # ***********************************************************************
  # Delete a committee.
  # ***********************************************************************
  def delete
    @committee = Committee.find(params[:id])
  end
  
  def destroy
    @committee = Committee.find(params[:id])
    @committee.destroy
    redirect_to(committees_path)
  end
  
  # ***********************************************************************
  # Other support methods.
  # ***********************************************************************
  private
  
  def committee_params
    params.require(:committee).permit(:name, :description)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.order(:name)
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
  end

  def edit
  end

  def delete
  end
  
  def create
  end
  
  def update
  end
  
  def destroy
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.order(:name)
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
  end

  def edit
  end

  def delete
  end
  
  def create
  end
  
  def update
  end
  
  def destroy
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  
  def index
    @positions = Position.order(:name)
  end

  def show
    @position = Position.find(params[:id])
  end

  def new
  end

  def edit
  end

  def delete
  end
  
  def create
  end
  
  def update
  end
  
  def destroy
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  
  def index
    @sponsors = Sponsor.order(:name)
  end

  def show
    @sponsor = Sponsor.find(params[:id])
  end

  def new
  end

  def edit
  end

  def delete
  end
  
  def create
  end
  
  def update
  end
  
  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/committees/delete.html.erb
<%= link_to("<< Back to List", committees_path, :class => "back-link") %>

<div>
    <h2>Delete Committee</h2>
    
    <%= form_for(@committee, :method => "delete") do |f| %>
        <p>Are you sure you want to permanently delete this committee?</p>
        <p><%= @committee.name %></p>
        <div>
            <%= f.submit("Delete Committee") %>
            
        </div>
    <% end %>
</div>

app/views/committees/edit.html.erb
<%= link_to("<< Back to List", committees_path, :class => "back-link") %>

<div>
    <h2>Update Committee</h2>
    <%= form_for(@committee) do |f| %>
        <table>
            <tr>
                <td>Name</td>
                <td><%= f.text_field(:name) %></td>
            </tr>
            <tr>
                <td>Description</td>
                <td><%= f.text_field(:description) %></td>
            </tr>
        </table>
        
        <div>
            <%= f.submit("Update Committee") %>
        </div>
    <% end %>
</div>

app/views/committees/index.html.erb
<div>
    <h2>Committees</h2>
    <%= link_to("Add new committee", new_committee_path, :class => "action new") %>
    <br /><br />
    <table>
        <tr>
            <td>#</td>
            <td>Name</td>
            <td></td>
        </tr>
        <% @committees.each do |committee| %>
        <tr>
            <td><%= committee.id %></td>
            <td><%= committee.name %></td>
            <td>
                <%= link_to("Show", committee_path(committee.id), :class => "action show") %>
                <%= link_to("Edit", edit_committee_path(committee.id), :class => "action edit") %>
                <%= link_to("Delete", delete_committee_path(committee.id), :class => "action delete") %>
            </td>
        </tr>
        <% end %>
    </table>
</div>

app/views/committees/new.html.erb
<%= link_to("<< Back to List", committees_path, :class => "back-link") %>

<div>
    <h2>Create Committee</h2>
    <%= form_for(@committee) do |f| %>
        <table>
            <tr>
                <td>Name</td>
                <td><%= f.text_field(:name) %></td>
            </tr>
            <tr>
                <td>Description</td>
                <td><%= f.text_field(:description) %></td>
            </tr>
        </table>
        
        <div>
            <%= f.submit("Create Committee") %>
        </div>
    <% end %>
</div>

app/views/committees/show.html.erb
<%= link_to("<< Back to list", committees_path, :class => "back-link") %>

<div>
    <h2>Show Committee</h2>
    
    <table>
        <tr>
            <td>Name</td>
            <td><%= @committee.name %></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%= @committee.description %></td>
        </tr>
    </table>
</div>

app/views/divisions/delete.html.erb
<h1>Divisions#delete</h1>
<p>Find me in app/views/divisions/delete.html.erb</p>

app/views/divisions/edit.html.erb
<h1>Divisions#edit</h1>
<p>Find me in app/views/divisions/edit.html.erb</p>

app/views/divisions/index.html.erb
<div>
    <h2>Divisions</h2>
    <%= link_to("Add new division", "#", :class => "action new") %>
    <br /><br />
    <table>
        <tr>
            <td>#</td>
            <td>Name</td>
            <td>Description</td>
            <td></td>
        </tr>
        <% @divisions.each do |division| %>
        <tr>
            <td><%= division.id %></td>
            <td><%= division.name %></td>
            <td><%= division.description %></td>
            <td>
                <%= link_to("Show", division_path(division.id), :class => "action show") %>
                <%= link_to("Edit", "#", :class => "action edit") %>
                <%= link_to("Delete", "#", :class => "action delete") %>
            </td>
        </tr>
        <% end %>
    </table>
</div>

app/views/divisions/new.html.erb
<h1>Divisions#new</h1>
<p>Find me in app/views/divisions/new.html.erb</p>

app/views/divisions/show.html.erb
<%= link_to("<< Back to list", divisions_path, :class => "back-link") %>

<div>
    <h2>Show Division</h2>
    
    <table>
        <tr>
            <td>Name</td>
            <td><%= @division.name %></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%= @division.description %></td>
        </tr>
    </table>
</div>

app/views/events/delete.html.erb
<h1>Events#delete</h1>
<p>Find me in app/views/events/delete.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div>
    <h2>Events</h2>
    <%= link_to("Add new event", "#", :class => "action new") %>
    <br /><br />
    <table>
        <tr>
            <td>#</td>
            <td>Name</td>
            <td>Link</td>
            <td></td>
        </tr>
        <% @events.each do |event| %>
        <tr>
            <td><%= event.id %></td>
            <td><%= event.name %></td>
            <td><%= event.link_to_event %></td>
            <td>
                <%= link_to("Show", event_path(event.id), :class => "action show") %>
                <%= link_to("Edit", "#", :class => "action edit") %>
                <%= link_to("Delete", "#", :class => "action delete") %>
            </td>
        </tr>
        <% end %>
    </table>
</div>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<%= link_to("<< Back to list", events_path, :class => "back-link") %>

<div>
    <h2>Show Event</h2>
    
    <table>
        <tr>
            <td>Name</td>
            <td><%= @event.name %></td>
        </tr>
        <tr>
            <td>Link to Event</td>
            <td><%= @event.link_to_event %></td>
        </tr>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/delete.html.erb
<h1>Members#delete</h1>
<p>Find me in app/views/members/delete.html.erb</p>

app/views/members/edit.html.erb
<h1>Members#edit</h1>
<p>Find me in app/views/members/edit.html.erb</p>

app/views/members/index.html.erb
<div>
    <h2>Members</h2>
    <%= link_to("Add new member", "#", :class => "action new") %>
    <br /><br />
    <table>
        <tr>
            <td>#</td>
            <td>Name</td>
            <td>Email</td>
            <td>Password</td>
            <td>Major</td>
            <td>Grad Year</td>
            <td>Member since</td>
            <td>Hometown</td>
            <td>Position</td>
            <td>Division</td>
            <td></td>
        </tr>
        <% @members.each do |member| %>
        <tr>
            <td><%= member.id %></td>
            <td><%= member.name %></td>
            <td><%= member.email %></td>
            <td><%= member.password %></td>
            <td><%= member.major %></td>
            <td><%= member.grad_year %></td>
            <td><%= member.member_since %></td>
            <td><%= member.hometown %></td>
            <td><%= member.position_id %></td>
            <td><%= member.division_id %></td>
            <td>
                <%= link_to("Show", member_path(member.id), :class => "action show") %>
                <%= link_to("Edit", "#", :class => "action edit") %>
                <%= link_to("Delete", "#", :class => "action delete") %>
            </td>
        </tr>
        <% end %>
    </table>
</div>

app/views/members/new.html.erb
<h1>Members#new</h1>
<p>Find me in app/views/members/new.html.erb</p>

app/views/members/show.html.erb
<%= link_to("<< Back to list", members_path, :class => "back-link") %>

<div>
    <h2>Show Member</h2>
    
    <table>
        <tr>
            <td>Name</td>
            <td><%= @member.name %></td>
        </tr>
        <tr>
            <td>Email</td>
            <td><%= @member.email %></td>
        </tr>
        <tr>
            <td>Password</td>
            <td><%= @member.password %></td>
        </tr>
        <tr>
            <td>Major</td>
            <td><%= @member.major %></td>
        </tr>
        <tr>
            <td>Grad Year</td>
            <td><%= @member.grad_year %></td>
        </tr>
        <tr>
            <td>Member since</td>
            <td><%= @member.member_since %></td>
        </tr>
        <tr>
            <td>Hometown</td>
            <td><%= @member.hometown %></td>
        </tr>
        <tr>
            <td>Position</td>
            <td><%= @member.position_id %></td>
        </tr>
        <tr>
            <td>Division</td>
            <td><%= @member.division_id %></td>
        </tr>
    </table>
</div>

app/views/positions/delete.html.erb
<h1>Positions#delete</h1>
<p>Find me in app/views/positions/delete.html.erb</p>

app/views/positions/edit.html.erb
<h1>Positions#edit</h1>
<p>Find me in app/views/positions/edit.html.erb</p>

app/views/positions/index.html.erb
<div>
    <h2>Positions</h2>
    <%= link_to("Add new position", "#", :class => "action new") %>
    <br /><br />
    <table>
        <tr>
            <td>#</td>
            <td>Name</td>
            <td>Type</td>
            <td></td>
        </tr>
        <% @positions.each do |position| %>
        <tr>
            <td><%= position.id %></td>
            <td><%= position.name %></td>
            <td><%= position.pos_type %></td>
            <td>
                <%= link_to("Show", position_path(position.id), :class => "action show") %>
                <%= link_to("Edit", "#", :class => "action edit") %>
                <%= link_to("Delete", "#", :class => "action delete") %>
            </td>
        </tr>
        <% end %>
    </table>
</div>

app/views/positions/new.html.erb
<h1>Positions#new</h1>
<p>Find me in app/views/positions/new.html.erb</p>

app/views/positions/show.html.erb
<%= link_to("<< Back to list", positions_path, :class => "back-link") %>

<div>
    <h2>Show Position</h2>
    
    <table>
        <tr>
            <td>Name</td>
            <td><%= @position.name %></td>
        </tr>
        <tr>
            <td>Type</td>
            <td><%= @position.pos_type %></td>
        </tr>
    </table>
</div>

app/views/sponsors/delete.html.erb
<h1>Sponsors#delete</h1>
<p>Find me in app/views/sponsors/delete.html.erb</p>

app/views/sponsors/edit.html.erb
<h1>Sponsors#edit</h1>
<p>Find me in app/views/sponsors/edit.html.erb</p>

app/views/sponsors/index.html.erb
<div>
    <h2>Sponsors</h2>
    <%= link_to("Add new sponsor", "#", :class => "action new") %>
    <br /><br />
    <table>
        <tr>
            <td>#</td>
            <td>Name</td>
            <td>Description</td>
            <td>Type</td>
            <td>Link to SEC</td>
            <td>Link to Sponsor</td>
            <td></td>
        </tr>
        <% @sponsors.each do |sponsor| %>
        <tr>
            <td><%= sponsor.id %></td>
            <td><%= sponsor.name %></td>
            <td><%= sponsor.description %></td>
            <td><%= sponsor.spn_type %></td>
            <td><%= sponsor.link_to_sec %></td>
            <td><%= sponsor.link_to_sponsor %></td>
            <td>
                <%= link_to("Show", sponsor_path(sponsor.id), :class => "action show") %>
                <%= link_to("Edit", "#", :class => "action edit") %>
                <%= link_to("Delete", "#", :class => "action delete") %>
            </td>
        </tr>
        <% end %>
    </table>
</div>

app/views/sponsors/new.html.erb
<h1>Sponsors#new</h1>
<p>Find me in app/views/sponsors/new.html.erb</p>

app/views/sponsors/show.html.erb
<%= link_to("<< Back to list", sponsors_path, :class => "back-link") %>

<div>
    <h2>Show Sponsor</h2>
    
    <table>
        <tr>
            <td>Name</td>
            <td><%= @sponsor.name %></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%= @sponsor.description %></td>
        </tr>
        <tr>
            <td>Type</td>
            <td><%= @sponsor.spn_type %></td>
        </tr>
        <tr>
            <td>Link to SEC</td>
            <td><%= @sponsor.link_to_sec %></td>
        </tr>
        <tr>
            <td>Link to Sponsor</td>
            <td><%= @sponsor.link_to_sponsor %></td>
        </tr>
    </table>
</div>